refactor folder structure report-upload, trufflehog converter added
xygeni/xygeni-extensions pull request #1
Opened 2024-05-17 07:28 UTC by vdlr

2024-05-17 10:14 UTC, lmrb-1968 requested changes
A typo found. Some (optional) chages were proposed.

2024-05-17 10:14 UTC, lmrb-1968 commented on extensions/report_upload/secrets/trufflehog/README.md
> +      loader:      my_org.xygeni.report-load.trufflehog.TruffleHogLoader
typo in package name, in the report-load atom:  Java packages do not allow hypens, underscores should be used instead. 

`my_org.xygeni.report-_oad.trufflehog.` is the correct package.

2024-05-17 10:14 UTC, lmrb-1968 commented on extensions/report_upload/secrets/trufflehog/README.md
> +### Add new Trufflehog report upload definition
Maybe the `Add new Trufflehog report upload definition` step is better to be placed as the last step, after the implementation classes are created and deployed. Otherwise a "ClassNotFound" exception will be rendered when running the report-upload command.

This is debatable, anyway. For anyone, having the class available is an obvious requisite. But end-users following blindly the instructions are more common that what one might think...

2024-05-17 10:14 UTC, lmrb-1968 commented on extensions/report_upload/secrets/trufflehog/README.md
> +### Setup the environment
(Optional)

Perhaps a `pom.xml` could be better. The user may simply set a variable with the scanner dir (where the obfuscated scanner jar contains all report-upload classes needed for compilation) and version, so the xygeni dependency could be resolved easily.

As this is common for all converters, perhaps a template or base `pom.xml` (that users may modify for implementing their own converters) could be provided.

Something with the following:

```xml
<properties>
        <!-- Xygeni scanner needs java 11 or higher to run -->
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>

        <!-- Put your own path. or refer to an environtment variable ${env.XYGENI_DIR} -->
        <xygeni.scanner.home>${env.XYGENI_DIR}</xygeni.scanner.home>
        <xygeni.scanner.version>6.16.0</xygeni.scanner.version>

        <!-- other properties here -->
</properties>

<dependencies>
        <!-- Reference to the xygeni-scanner uberjar -->
        <dependency>
            <groupId>io.xygeni</groupId>
            <artifactId>xygeni-scanner</artifactId>
            <version>${xygeni.scanner.version}</version>
            <scope>system</scope>
            <systemPath>${xygeni.scanner.home}/lib/xygeni-scanner-${xygeni.scanner.version}.jar</systemPath>
        </dependency>
        
         <!-- Add additional dependencies here -->
</dependencies>

```

Also the `exec-maven-plugin` could be used for running shell scripts (we assume linux for simplicity in our scripts published in xygeni-extensions, under windows it should be be too difficult for a developer to create the necessary conversions to PowerShell). 

```xml
            <plugin>
                <artifactId>exec-maven-plugin</artifactId>
                <groupId>org.codehaus.mojo</groupId>
                <executions>
                    <execution>
                        <id>Generate rule files</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>${basedir}/bin/generate_rules.sh</executable>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```


Take a look at exporter/kiuwan/pom.xml, which not only compiles and packages the classes into a jar but also runs a generate_rules.sh.

2024-05-17 10:14 UTC, lmrb-1968 commented on extensions/report_upload/secrets/trufflehog/lib/copy-here.txt
See the previous comment on the pom.xml. Perhaps it is better to provide dependencies mostly resolved, using the scanner JAR libraries resolved with `<scope>system</scope><systemPath>...</systemPath>`. Providing this saves the user many headaches.

BTW, why is the `apiguardian-api` library listed here?

2024-05-20 06:14 UTC, vdlr commented on extensions/report_upload/secrets/trufflehog/README.md
> +### Add new Trufflehog report upload definition
right! I changed it

2024-05-20 06:16 UTC, vdlr commented on extensions/report_upload/secrets/trufflehog/README.md
> +### Setup the environment
I added a pom and fix the folder structure. Some refactor is still required to remove depsdoctor core/commons dependencies

2024-05-20 08:28 UTC, lmrb-1968 approved these changes
LGTM!

2024-05-20 08:28 UTC, merged